# Generated by Django 3.1.4 on 2020-12-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook', '0002_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
