# Generated by Django 3.1.4 on 2020-12-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook', '0003_story_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
