# Generated by Django 3.1.4 on 2020-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook', '0004_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_first_page',
            field=models.BooleanField(default=False),
        ),
    ]
